CREATE TABLE IF NOT EXISTS Users
(
    user_id       INT AUTO_INCREMENT PRIMARY KEY,
    username      VARCHAR(255) UNIQUE NOT NULL,
    password      VARCHAR(255)        NOT NULL,
    email         VARCHAR(255) UNIQUE NOT NULL,
    full_name     VARCHAR(255)        NOT NULL,
    user_type     ENUM('Student', 'Teacher', 'Admin') NOT NULL,
    photo_address VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Teachers
(
    teacher_id  INT AUTO_INCREMENT PRIMARY KEY,
    user_id        INT UNIQUE,
    bio            TEXT,
    specialization VARCHAR(255),
    FOREIGN KEY (user_id) REFERENCES Users (user_id)
);

CREATE TABLE IF NOT EXISTS Categories
(
    category_id INT AUTO_INCREMENT PRIMARY KEY,
    name        VARCHAR(255) UNIQUE,
    description TEXT
);

CREATE TABLE IF NOT EXISTS Courses
(
    course_id     INT AUTO_INCREMENT PRIMARY KEY,
    title         VARCHAR(255) NOT NULL,
    description   TEXT,
    teacher_id INT,
    category_id   INT,
    photo_address VARCHAR(255),
    rating        DECIMAL(3, 2),
    lessons_count INT,
    duration_hour INT,
    language      VARCHAR(50),
    price         DECIMAL(10, 2),
    FOREIGN KEY (teacher_id) REFERENCES Teachers (teacher_id),
    FOREIGN KEY (category_id) REFERENCES Categories (category_id)
);

CREATE TABLE IF NOT EXISTS Enrollments
(
    enrollment_id     INT AUTO_INCREMENT PRIMARY KEY,
    user_id           INT,
    course_id         INT,
    enrollment_date   DATE,
    FOREIGN KEY (user_id) REFERENCES Users (user_id),
    FOREIGN KEY (course_id) REFERENCES Courses (course_id),
    UNIQUE KEY unique_enrollment (user_id, course_id)
);

-- Table for Blogs
CREATE TABLE IF NOT EXISTS Blogs (
    blog_id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    summary VARCHAR(512) NOT NULL,
    content TEXT,
    author_id INT,
    category_id INT,
    photo_address VARCHAR(255),
    post_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (author_id) REFERENCES Users(user_id),
    FOREIGN KEY (category_id) REFERENCES Categories(category_id)
);

-- Table for Comments
CREATE TABLE IF NOT EXISTS Comments (
    comment_id INT AUTO_INCREMENT PRIMARY KEY,
    blog_id INT,
    user_id INT,
    comment_text TEXT,
    comment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (blog_id) REFERENCES Blogs(blog_id),
    FOREIGN KEY (user_id) REFERENCES Users(user_id)
);

-- Add Categories
INSERT INTO Categories (name, description)
VALUES
    ('English', 'Courses related to English language skills and literature.'),
    ('Chemistry', 'Courses focusing on principles and practices in the field of Chemistry.'),
    ('Physics', 'Courses covering principles and practices in the field of Physics.'),
    ('Math', 'Courses involving mathematical concepts and problem-solving techniques.'),
    ('Web Design', 'Courses related to web design principles and practices.'),
    ('Web Development', 'Courses focusing on designing applications for various platforms.');

-- Add Users
INSERT INTO Users (username, password, email, full_name, user_type, photo_address)
VALUES ('admin', 'admin', 'admin@website.com', 'AmirHossein', 'admin', 'admin_photo.jpg'),
        -- Teachers
        ('teacher1_id', 'teacher1_password', 'john_smith@example.com', 'John Smith', 'Teacher', 'default.jpg'),
        ('teacher2_id', 'teacher2_password', 'jane_muller@example.com', 'Jane Müller', 'Teacher', 'default.jpg'),
        ('teacher3_id', 'teacher3_password', 'alex_schmidt@example.com', 'Alex Schmidt', 'Teacher', 'default.jpg'),
        ('teacher4_id', 'teacher4_password', 'emma_wagner@example.com', 'Emma Wagner', 'Teacher', 'default.jpg'),
        ('teacher5_id', 'teacher5_password', 'ali_fischer@example.com', 'Ali Fischer', 'Teacher', 'default.jpg'),
        ('teacher6_id', 'teacher6_password', 'ommar_katup@example.com', 'Ommar J. Katup', 'Teacher', 'default.jpg'),
        ('teacher7_id', 'teacher7_password', 'david_berger@example.com', 'David Berger', 'Teacher', 'default.jpg'),
        ('teacher8_id', 'teacher8_password', 'mary_richter@example.com', 'Mary Richter', 'Teacher', 'default.jpg'),
        -- students
        ('std1', '123@1230', 'Michael_Student@example.com', 'Michael Müller', 'student', 'default.jpg'),
        ('std2', '123@1231', 'Olivia_Learner@example.com', 'Olivia Lehmann', 'student', 'default.jpg'),
        ('std3', '123@1232', 'Liam_Apprentice@example.com', 'Liam Andersen', 'student', 'default.jpg'),
        ('std4', '123@1233', 'Ava_Trainee@example.com', 'Ava Thomsen', 'student', 'default.jpg'),
        ('std5', '123@1234', 'Noah_Pupil@example.com', 'Noah Pedersen', 'student', 'default.jpg'),
        ('std6', '123@1235', 'Isabella_Scholar@example.com', 'Isabella Schmitt', 'student', 'default.jpg'),
        ('std7', '123@1237', 'Sophia_Apprentice@example.com', 'Sophia Arnold', 'student', 'default.jpg'),
        ('std8', '123@1238', 'Lucas_Learner@example.com', 'Lucas Lehner', 'student', 'default.jpg'),
        ('std9', '123@1239', 'Amelia_Student@example.com', 'Amelia Schneider', 'student', 'default.jpg'),
        ('std10', '123@1240', 'Mia_Trainee@example.com', 'Mia Wagner', 'student', 'default.jpg'),
        ('std11', '123@1241', 'Ethan_Pupil2@example.com', 'Ethan Weber', 'student', 'default.jpg'),
        ('std12', '123@1242', 'Harper_Scholar@example.com', 'Harper Keller', 'student', 'default.jpg'),
        ('std13', '123@1243', 'William_Learner@example.com', 'William Lange', 'student', 'default.jpg'),
        ('std14', '123@1244', 'Abigail_Trainee@example.com', 'Abigail Vogel', 'student', 'default.jpg'),
        ('std15', '123@1245', 'Logan_Pupil@example.com', 'Logan Becker', 'student', 'default.jpg'),
        ('std16', '123@1246', 'Emma_Student@example.com', 'Emma Stein', 'student', 'default.jpg'),
        ('std17', '123@1247', 'Jackson_Learner@example.com', 'Jackson Hartmann', 'student', 'default.jpg'),
        ('std18', '123@1248', 'Sophie_Apprentice@example.com', 'Sophie Schreiber', 'student', 'default.jpg'),
        ('std19', '123@1249', 'Aiden_Trainee@example.com', 'Aiden Meier', 'student', 'default.jpg'),
        ('std20', '123@1250', 'Scarlett_Pupil@example.com', 'Scarlett Jansen', 'student', 'default.jpg'),
        ('std21', '123@1251', 'Liam_Student@example.com', 'Liam Richter', 'student', 'default.jpg'),
        ('std22', '123@1252', 'Ava_Learner@example.com', 'Ava Neumann', 'student', 'default.jpg'),
        ('std23', '123@1253', 'Noah_Apprentice@example.com', 'Noah Hahn', 'student', 'default.jpg'),
        ('std24', '123@1254', 'Olivia_Trainee@example.com', 'Olivia Becker', 'student', 'default.jpg'),
        ('std25', '123@1255', 'Ethan_Pupil@example.com', 'Ethan König', 'student', 'default.jpg'),
        ('std26', '123@1256', 'Isabella_Student@example.com', 'Isabella Vogt', 'student', 'default.jpg'),
        ('std27', '123@1257', 'Mason_Learner@example.com', 'Mason Winkler', 'student', 'default.jpg'),
        ('std28', '123@1258', 'Ella_Apprentice@example.com', 'Ella Müller', 'student', 'default.jpg'),
        ('std29', '123@1259', 'Logan_Trainee@example.com', 'Logan Krüger', 'student', 'default.jpg'),
        ('std30', '123@1260', 'Avery_Pupil@example.com', 'Avery Koch', 'student', 'default.jpg');

-- Add Teachers
INSERT INTO Teachers (user_id, bio, specialization)
VALUES
    (2, 'John Smith is an experienced Teacher with a passion for web development.', 'Web Development'),
    (3, 'Jane Müller specializes in graphic design and has a keen eye for aesthetics.', 'Graphic Design'),
    (4, 'Alex Schmidt is a skilled mathematics Teacher who makes learning fun and engaging.', 'Mathematics'),
    (5, 'Chemistry expert with a focus on practical experiments and hands-on learning.', 'Chemistry'),
    (6, 'Ali Fischer is a dedicated Teacher with a focus on English.', 'English'),
    (7, 'Ommar J. Katup is an expert in health education and wellness programs.', 'Health Education'),
    (8, 'David Berger has a passion for sports education and encourages an active lifestyle.', 'Sports Education'),
    (9, 'Physics enthusiast specializing in theoretical and applied physics.', 'Physics');

-- Add Courses
INSERT INTO Courses (title, description, teacher_id, category_id, photo_address, rating, lessons_count, duration_hour, language, price)
VALUES
    ('English Basics', 'Get started with an introduction to fundamental English grammar and vocabulary. This course covers essential language skills for beginners looking to build a strong foundation in English.', 5, 1, 'default.jpg', 4.5, 12, 20, 'English', 49.99),
    ('Advanced English Composition', 'Take your writing skills to the next level with this advanced course in English composition. Explore intricate aspects of the language and refine your ability to articulate thoughts with precision.', 5, 1, 'default.jpg', 4.8, 15, 25, 'English', 69.99),
    ('English Literature Classics', 'Embark on a journey through the timeless masterpieces of English literature. Dive into classic works that have shaped the literary landscape, gaining insights into the cultural and historical contexts.', 5, 1, 'default.jpg', 4.7, 10, 18, 'English', 59.99),
    ('Business English Communication', 'Elevate your communication skills in professional settings with this course. Learn to convey ideas effectively, write compelling business documents, and engage in successful business communication.', 5, 1, 'default.jpg', 4.6, 14, 22, 'English', 54.99),
    ('English Pronunciation Mastery', 'Achieve mastery in English pronunciation through detailed guidance on nuances and phonetic principles. Enhance your spoken English skills and sound more natural and confident.', 5, 1, 'default.jpg', 4.9, 8, 15, 'English', 44.99),
    ('English for Academic Writing', 'Hone your academic writing skills in English with this comprehensive course. Learn techniques and strategies to produce well-structured and compelling academic documents.', 5, 1, 'default.jpg', 4.8, 13, 21, 'English', 64.99),
    ('Conversational English Skills', 'Improve your conversational skills across various English contexts. Engage in dynamic discussions and practice effective communication for diverse social and professional situations.', 5, 1, 'default.jpg', 4.7, 16, 28, 'English', 59.99),
    ('English for Travelers', 'Equip yourself with essential English phrases and expressions for seamless travel experiences. Learn language skills specifically tailored for effective communication during your journeys.', 5, 1, 'default.jpg', 4.6, 10, 15, 'English', 39.99),
    ('Creative Writing in English', 'Unleash your creativity through writing in the English language. This course offers a platform for self-expression and exploration of various writing styles and genres.', 5, 1, 'default.jpg', 4.9, 12, 20, 'English', 49.99),
    ('English Language Proficiency Exam Prep', 'Prepare confidently for English language proficiency exams with this comprehensive exam prep course. Covering all aspects of language proficiency, it ensures you are well-equipped for success.', 5, 1, 'default.jpg', 4.8, 14, 25, 'English', 69.99),
    ('Introduction to Chemistry', 'Delve into the basic principles and fundamental concepts of chemistry with this introductory course. Explore the building blocks of matter, chemical reactions, and key scientific principles in the world of chemistry.', 4, 2, 'default.jpg', 4.5, 12, 20, 'English', 49.99),
    ('Organic Chemistry Fundamentals', 'Embark on a journey through the intricate world of organic chemistry. Understand the fundamental principles governing the structure, properties, and reactions of organic compounds.', 4, 2, 'default.jpg', 4.8, 15, 25, 'English', 69.99),
    ('Inorganic Chemistry Principles', 'Dive deep into the theories and principles of inorganic chemistry. Explore the behavior and properties of inorganic compounds, gaining a comprehensive understanding of this diverse field.', 4, 2, 'default.jpg', 4.7, 10, 18, 'English', 59.99),
    ('Analytical Chemistry Techniques', 'Master the techniques employed in analytical chemistry with this practical course. Learn to analyze and quantify chemical substances using various methods and instruments.', 4, 2, 'default.jpg', 4.6, 14, 22, 'English', 54.99),
    ('Physical Chemistry Applications', 'Explore the practical applications of physical chemistry in this comprehensive course. Understand how physical principles contribute to various scientific and industrial applications.', 4, 2, 'default.jpg', 4.9, 8, 15, 'English', 44.99),
    ('Chemical Kinetics and Thermodynamics', 'Gain insights into the dynamic world of chemical kinetics and thermodynamics. Explore the rates of chemical reactions and the energy changes associated with them.', 4, 2, 'default.jpg', 4.8, 13, 21, 'English', 64.99),
    ('Environmental Chemistry', 'Investigate the impact of chemical processes on the environment with this course. Understand the role of chemistry in addressing environmental challenges and sustaining a healthy planet.', 4, 2, 'default.jpg', 4.7, 16, 28, 'English', 59.99),
    ('Biochemistry Essentials', 'Discover essential concepts and applications of biochemistry in this foundational course. Explore the molecular processes within living organisms and the role of chemistry in life sciences.', 4, 2, 'default.jpg', 4.6, 10, 15, 'English', 39.99),
    ('Chemistry of Materials', 'Explore the fascinating world of materials and substances with a focus on chemistry. Understand the properties and applications of different materials, providing insights into the advancement of technology.', 4, 2, 'default.jpg', 4.9, 12, 20, 'English', 49.99),
    ('Advanced Topics in Chemistry', 'Engage with advanced topics and cutting-edge research in the field of chemistry. Stay at the forefront of scientific developments and contribute to the advancement of chemical knowledge.', 4, 2, 'default.jpg', 4.8, 14, 25, 'English', 69.99),
    ('Classical Mechanics', 'Embark on a comprehensive exploration of classical mechanics, unraveling the fundamental principles governing the motion of objects. Covering concepts like Newtonian mechanics, kinematics, and dynamics, this course provides a solid foundation in classical physics.', 8, 3, 'default.jpg', 4.5, 12, 20, 'English', 49.99),
    ('Quantum Physics Basics', 'Take a journey into the fascinating world of quantum physics with this introductory course. Explore the foundational principles and theories that govern the behavior of particles at the quantum level, challenging our classical understanding of the physical universe.', 8, 3, 'default.jpg', 4.8, 15, 25, 'English', 69.99),
    ('Thermodynamics and Statistical Mechanics', 'Delve into the principles of thermodynamics and statistical mechanics, exploring the behavior of matter and energy. Gain insights into concepts like entropy, heat transfer, and the statistical nature of physical systems.', 8, 3, 'default.jpg', 4.7, 10, 18, 'English', 59.99),
    ('Electromagnetism Principles', 'Uncover the laws and principles governing electromagnetism, a cornerstone of modern physics. From Maxwells equations to electromagnetic waves, this course provides a thorough understanding of the electromagnetic forces shaping our world.', 8, 3, 'default.jpg', 4.6, 14, 22, 'English', 54.99),
    ('Nuclear Physics Fundamentals', 'Explore fundamental concepts in nuclear physics, delving into the structure and behavior of atomic nuclei. Cover topics like nuclear reactions, radioactivity, and nuclear energy, gaining insights into the heart of matter.', 8, 3, 'default.jpg', 4.9, 8, 15, 'English', 44.99),
    ('Optics and Light', 'Immerse yourself in the world of optics and light with this course. Explore the principles governing the behavior of light, optical instruments, and their applications in various fields, from microscopy to telecommunications.', 8, 3, 'default.jpg', 4.8, 13, 21, 'English', 64.99),
    ('Astrophysics Explained', 'Embark on an introductory journey into the captivating realm of astrophysics. Explore the fundamental principles governing celestial bodies, cosmic phenomena, and the vastness of the universe, unraveling the mysteries of the cosmos.', 8, 3, 'default.jpg', 4.7, 16, 28, 'English', 59.99),
    ('Particle Physics Journey', 'Embark on a fascinating journey into the world of particle physics, exploring the fundamental building blocks of matter. Delve into concepts like quarks, leptons, and the forces that govern particle interactions, unraveling the secrets of the subatomic realm.', 8, 3, 'default.jpg', 4.6, 10, 15, 'English', 39.99),
    ('Relativity Theory', 'Explore the groundbreaking theory of relativity and its profound implications on our understanding of space and time. Covering both special and general relativity, this course offers a deep dive into Einstein revolutionary contributions to theoretical physics.', 8, 3, 'default.jpg', 4.9, 12, 20, 'English', 49.99),
    ('Advanced Topics in Physics', 'Engage with advanced topics and cutting-edge research in the field of physics. Stay at the forefront of scientific developments, exploring topics that push the boundaries of our understanding of the physical universe.', 8, 3, 'default.jpg', 4.8, 14, 25, 'English', 69.99),
    ('Algebra Fundamentals', 'Establish a robust understanding of algebraic concepts and problem-solving strategies in this foundational course. Covering topics such as equations, inequalities, and functions, this course lays the groundwork for advanced mathematical exploration.', 3, 4, 'default.jpg', 4.5, 12, 20, 'English', 49.99),
    ('Geometry Explained', 'Delve into the principles and applications of geometry, unraveling the relationships between shapes and spaces in real-world scenarios. From Euclidean geometry to applications in architecture and design, this course provides a comprehensive exploration.', 3, 4, 'default.jpg', 4.8, 15, 25, 'English', 69.99),
    ('Calculus Basics', 'Embark on an introductory journey into the basics of calculus and its practical applications. Covering limits, derivatives, and integrals, this course lays the groundwork for understanding change and motion in various scientific and mathematical contexts.', 3, 4, 'default.jpg', 4.7, 10, 18, 'English', 59.99),
    ('Statistics for Beginners', 'Unlock the world of statistics with this beginner-friendly course. Learn essential statistical concepts and methods for data analysis, enabling you to interpret and draw meaningful insights from data in diverse fields.', 3, 4, 'default.jpg', 4.6, 14, 22, 'English', 54.99),
    ('Trigonometry Mastery', 'Master the principles of trigonometry and their applications in this comprehensive course. From angles and trigonometric functions to solving complex problems, this course provides a deep understanding of this fundamental branch of mathematics.', 3, 4, 'default.jpg', 4.9, 8, 15, 'English', 44.99),
    ('Differential Equations', 'Study the intricate world of differential equations and their role in various scientific fields. Explore the mathematical models that describe change and phenomena, gaining insights into differential equations and their applications.', 3, 4, 'default.jpg', 4.8, 13, 21, 'English', 64.99),
    ('Mathematical Proofs', 'Immerse yourself in the art of mathematical proofs and logical reasoning. Develop the skills to construct and understand rigorous mathematical arguments, providing a solid foundation for advanced mathematical thinking.', 3, 4, 'default.jpg', 4.7, 16, 28, 'English', 59.99),
    ('Linear Algebra Essentials', 'Explore essential concepts in linear algebra and their wide-ranging applications. From vector spaces to matrix operations, this course provides the tools to understand and solve complex problems in diverse scientific and engineering domains.', 3, 4, 'default.jpg', 4.6, 10, 15, 'English', 39.99),
    ('Number Theory Explorations', 'Embark on a journey into the fascinating world of number theory and its profound implications. Explore the properties and relationships of numbers, uncovering the beauty and elegance inherent in this branch of mathematics.', 3, 4, 'default.jpg', 4.9, 12, 20, 'English', 49.99),
    ('Advanced Mathematical Topics', 'Engage with advanced topics and cutting-edge research in the field of mathematics. Stay at the forefront of mathematical developments, exploring topics that push the boundaries of our understanding of abstract and applied mathematics.', 3, 4, 'default.jpg', 4.8, 14, 25, 'English', 69.99),
    ('Introduction to Web Design', 'Embark on your web design journey by learning the fundamentals of web design and HTML/CSS. This course introduces the basics of creating visually appealing and functional websites, laying the groundwork for a successful career in web development.', 1, 5, 'default.jpg', 4.5, 10, 20, 'English', 49.99),
    ('Responsive Web Design', 'Master the art of creating responsive and mobile-friendly websites with this comprehensive course. Explore design techniques and best practices to ensure your websites look stunning and function seamlessly across various devices.', 1, 5, 'default.jpg', 4.7, 15, 25, 'English', 69.99),
    ('Advanced CSS Techniques', 'Elevate your web design skills with this course on advanced CSS techniques. Dive into modern CSS features and styling practices, gaining the expertise to create visually striking and dynamic web pages.', 1, 5, 'default.jpg', 4.8, 12, 18, 'English', 59.99),
    ('User Interface (UI) Design', 'Delve into the world of UI design and create intuitive, user-friendly interfaces for websites and applications. Explore the principles of effective design, usability, and user experience to enhance the overall quality of your web projects.', 1, 5, 'default.jpg', 4.6, 14, 22, 'English', 64.99),
    ('JavaScript for Web Designers', 'Enhance your web design capabilities by learning JavaScript. This course explores the role of JavaScript in creating interactive and dynamic web pages, allowing you to add functionality and interactivity to your designs.', 1, 5, 'default.jpg', 4.4, 18, 30, 'English', 79.99),
    ('Web Design Portfolio Development', 'Build a compelling web design portfolio that showcases your skills and projects. This course guides you through the process of creating a professional portfolio that will impress potential clients and employers.', 1, 5, 'default.jpg', 4.9, 8, 15, 'English', 54.99),
    ('Graphic Design for the Web', 'Combine graphic design principles with web design to create visually stunning websites. This course explores the integration of graphic elements, color theory, and layout design for impactful and aesthetically pleasing web projects.', 1, 5, 'default.jpg', 4.7, 16, 28, 'English', 74.99),
    ('Web Accessibility Standards', 'Ensure your websites are accessible to all users by adhering to web accessibility standards. This course covers the principles and techniques for designing inclusive and accessible web interfaces.', 1, 5, 'default.jpg', 4.5, 10, 20, 'English', 59.99),
    ('E-commerce Website Design', 'Learn the ins and outs of creating effective e-commerce websites for online businesses. This course covers the design and functionality aspects crucial for a successful and visually appealing online shopping experience.', 1, 5, 'default.jpg', 4.6, 14, 24, 'English', 69.99),
    ('Web Design Best Practices', 'Stay at the forefront of modern web design by learning the best practices and industry standards. This course covers the latest trends, techniques, and strategies to ensure your web designs meet the highest standards of quality and usability.', 1, 5, 'default.jpg', 4.8, 12, 18, 'English', 59.99),
    ('Introduction to Web Development', 'Embark on your web development journey by mastering the fundamentals of web development and HTML/CSS. This introductory course provides a solid foundation for creating dynamic and interactive websites, laying the groundwork for a successful career in web development.', 1, 6, 'default.jpg', 4.5, 10, 20, 'English', 49.99),
    ('Responsive Web Design and Development', 'Master the art of creating responsive and mobile-friendly websites with this comprehensive course. Explore the integration of design principles with development techniques, ensuring your websites are visually appealing and function seamlessly across devices.', 1, 6, 'default.jpg', 4.7, 15, 25, 'English', 69.99),
    ('Advanced JavaScript Programming', 'Elevate your JavaScript skills with this advanced programming course. Dive into modern JavaScript techniques, covering topics such as asynchronous programming, ES6 features, and advanced concepts essential for cutting-edge web development.', 1, 6, 'default.jpg', 4.8, 12, 18, 'English', 59.99),
    ('Server-side Development with Node.js', 'Explore server-side web development using Node.js, a powerful and versatile JavaScript runtime. This course covers the essentials of building scalable and efficient server-side applications, expanding your skill set in the world of web development.', 1, 6, 'default.jpg', 4.6, 14, 22, 'English', 64.99),
    ('Database Design and Management', 'Gain expertise in database design principles and management for web applications. This course covers the fundamentals of database systems, SQL, and effective database management strategies crucial for developing robust and scalable web solutions.', 1, 6, 'default.jpg', 4.4, 18, 30, 'English', 79.99),
    ('Full-Stack Web Development', 'Become a versatile full-stack developer by mastering both front-end and back-end technologies. This comprehensive course covers the entire web development stack, empowering you to create end-to-end solutions for diverse projects.', 1, 6, 'default.jpg', 4.9, 8, 15, 'English', 54.99),
    ('Web Security and Best Practices', 'Ensure secure web development with this course on web security and best practices. Explore techniques and strategies to safeguard web applications against potential threats, keeping your projects secure and trustworthy.', 1, 6, 'default.jpg', 4.7, 16, 28, 'English', 74.99),
    ('API Development and Integration', 'Master the development and integration of APIs to enhance the functionality of your web applications. This course covers the creation, documentation, and integration of APIs, expanding your capabilities in building dynamic and connected web projects.', 1, 6, 'default.jpg', 4.5, 10, 20, 'English', 59.99),
    ('Web Development Frameworks', 'Explore popular web development frameworks to streamline and enhance your projects. This course introduces frameworks that provide efficient and scalable solutions, accelerating your web development process.', 1, 6, 'default.jpg', 4.6, 14, 24, 'English', 69.99),
    ('Web Development Project Management', 'Learn effective project management strategies tailored for successful web development projects. This course covers project planning, execution, and collaboration techniques to ensure the timely and efficient delivery of your web solutions.', 1, 6, 'default.jpg', 4.8, 12, 18, 'English', 59.99);

-- Add enrollments
INSERT INTO Enrollments (user_id, course_id, enrollment_date)
VALUES
    (1, 1, '2024-01-21'),
    (1, 2, '2024-01-21'),
    (1, 3, '2024-01-21'),
    (1, 4, '2024-01-21'),
    (1, 5, '2024-01-21'),
    (2, 1, '2024-01-22'),
    (2, 2, '2024-01-22'),
    (2, 3, '2024-01-22'),
    (2, 4, '2024-01-22'),
    (3, 1, '2024-01-23'),
    (3, 2, '2024-01-23'),
    (3, 3, '2024-01-23'),
    (3, 14, '2024-01-23'),
    (3, 5, '2024-01-23'),
    (3, 4, '2024-01-24'),
    (5, 5, '2024-01-25'),
    (6, 6, '2024-01-26'),
    (7, 1, '2024-01-27'),
    (7, 2, '2024-01-27'),
    (7, 3, '2024-01-27'),
    (7, 4, '2024-01-27'),
    (7, 5, '2024-01-27'),
    (7, 6, '2024-01-27'),
    (7, 7, '2024-01-27'),
    (8, 8, '2024-01-28'),
    (9, 9, '2024-01-29'),
    (10, 10, '2024-01-30'),
    (11, 11, '2024-01-31'),
    (12, 12, '2024-02-01'),
    (13, 13, '2024-02-02'),
    (14, 14, '2024-02-03'),
    (15, 15, '2024-02-04'),
    (16, 16, '2024-02-05'),
    (17, 17, '2024-02-06'),
    (18, 18, '2024-02-07'),
    (19, 19, '2024-02-08'),
    (20, 1, '2024-02-09'),
    (20, 11, '2024-02-09'),
    (20, 3, '2024-02-09'),
    (20, 4, '2024-02-09'),
    (20, 5, '2024-02-09'),
    (20, 6, '2024-02-09'),
    (20, 7, '2024-02-09'),
    (20, 8, '2024-02-09'),
    (20, 21, '2024-02-09'),
    (20, 20, '2024-02-09'),
    (21, 21, '2024-02-10'),
    (22, 22, '2024-02-11'),
    (23, 23, '2024-02-12'),
    (24, 24, '2024-02-13'),
    (25, 25, '2024-02-14'),
    (26, 26, '2024-02-15'),
    (27, 27, '2024-02-16'),
    (28, 28, '2024-02-17'),
    (29, 29, '2024-02-18'),
    (30, 30, '2024-02-19');

-- Add blogs
INSERT INTO Blogs (title, summary, content, author_id, category_id, photo_address, post_date)
VALUES
    ('Improving Vocabulary', 'Enhance your language skills by learning effective vocabulary-building techniques.', 'In this blog post, we explore various methods to improve your vocabulary, including reading, word games, and language apps. Strengthening your vocabulary is a crucial step in mastering the English language.', 1, 1, 'default.jpg', CURRENT_TIMESTAMP),
    ('Mastering Grammar Rules', 'Navigate the intricacies of English grammar with this comprehensive guide.', 'Delve into the world of English grammar and acquire a solid understanding of its rules and structures. This blog post covers common grammar pitfalls and provides tips for mastering this essential aspect of language.', 1, 1, 'default.jpg', CURRENT_TIMESTAMP),
    ('Exploring English Literature Classics', 'Embark on a literary journey through timeless English literature classics.', 'Discover the beauty and depth of classic English literature in this blog post. We explore iconic works by renowned authors, offering insights into their themes, characters, and enduring relevance in todays world.', 1, 1, 'default.jpg', CURRENT_TIMESTAMP),
    ('Effective Business Communication', 'Unlock the secrets of effective business communication in the English language.', 'This blog post focuses on honing your English communication skills in a business context. Learn strategies for crafting professional emails, conducting meetings, and delivering impactful presentations.', 1, 1, 'default.jpg', CURRENT_TIMESTAMP),
    ('The Art of Creative Writing', 'Unleash your creativity through the art of writing in the English language.', 'Explore the world of creative writing in this blog post. Whether youre a novice or an experienced writer, discover techniques to express your thoughts, emotions, and imagination through captivating English prose.', 1, 1, 'default.jpg', CURRENT_TIMESTAMP),
    ('Introduction to Chemistry Basics', 'Explore the fundamental principles and concepts of chemistry.', 'In this blog post, we delve into the basics of chemistry, covering essential principles and concepts that form the foundation of the field. Whether you are a student or a curious enthusiast, this blog provides insights into the intriguing world of chemistry.', 1, 2, 'default.jpg', CURRENT_TIMESTAMP),
    ('The Wonders of Organic Chemistry', 'Discover the fascinating world of organic chemistry and its applications.', 'Organic chemistry is a captivating branch of the discipline, focusing on carbon compounds and their properties. This blog post highlights the fundamentals of organic chemistry, exploring its relevance in various industries and everyday life.', 1, 2, 'default.jpg', CURRENT_TIMESTAMP),
    ('Exploring Inorganic Chemistry Principles', 'Embark on a journey through the principles and theories of inorganic chemistry.', 'Dive into the realm of inorganic chemistry with this comprehensive blog post. Gain insights into the principles and theories that govern the behavior of inorganic compounds, from fundamental concepts to advanced topics.', 1, 2, 'default.jpg', CURRENT_TIMESTAMP),
    ('Analytical Chemistry Techniques Unveiled', 'Uncover the techniques used in analytical chemistry for precise analysis.', 'Analytical chemistry plays a crucial role in determining the composition of substances. This blog post explores various analytical techniques, shedding light on their applications and significance in scientific research and industrial processes.', 1, 2, 'default.jpg', CURRENT_TIMESTAMP),
    ('Applications of Physical Chemistry', 'Explore the diverse applications of physical chemistry in various fields.', 'Physical chemistry bridges the gap between physics and chemistry, offering insights into the physical properties and behavior of matter. This blog post discusses the applications of physical chemistry, showcasing its relevance in different scientific disciplines.', 1, 2, 'default.jpg', CURRENT_TIMESTAMP),
    ('Understanding Classical Mechanics', 'Explore the fundamental principles of classical mechanics.', 'This blog post provides an in-depth exploration of classical mechanics, covering foundational principles such as Newtonian mechanics and kinematics. Whether youre a physics enthusiast or a student, delve into the fascinating world of classical mechanics.', 1, 3, 'default.jpg', CURRENT_TIMESTAMP),
    ('Introduction to Quantum Physics', 'Embark on a journey into the basics of quantum physics.', 'Quantum physics is a captivating field that challenges our understanding of the universe. In this blog post, we introduce the basic concepts of quantum physics, exploring phenomena such as superposition and quantum entanglement.', 1, 3, 'default.jpg', CURRENT_TIMESTAMP),
    ('Exploring Thermodynamics and Statistical Mechanics', 'Study thermodynamics and statistical mechanics concepts in-depth.', 'Thermodynamics and statistical mechanics play a crucial role in understanding the behavior of physical systems. This blog post delves into the principles of thermodynamics and statistical mechanics, providing insights into their applications and significance.', 1, 3, 'default.jpg', CURRENT_TIMESTAMP),
    ('Principles of Electromagnetism', 'Learn the principles and laws governing electromagnetism.', 'Electromagnetism is a cornerstone of physics, influencing various technological advancements. In this blog post, we explore the principles of electromagnetism, covering Maxwell equations and the behavior of electromagnetic fields.', 1, 3, 'default.jpg', CURRENT_TIMESTAMP),
    ('Fundamentals of Nuclear Physics', 'Gain insights into fundamental concepts in the field of nuclear physics.', 'Nuclear physics is a fascinating discipline that explores the properties and behavior of atomic nuclei. This blog post covers fundamental concepts in nuclear physics, from nuclear structure to radioactivity and nuclear reactions.', 1, 3, 'default.jpg', CURRENT_TIMESTAMP),
    ('Foundations of Algebra', 'Build a strong foundation in algebraic concepts and problem-solving.', 'This blog post serves as a guide to mastering the foundations of algebra. Whether you are a student or an enthusiast, explore essential algebraic concepts and problem-solving techniques to strengthen your mathematical skills.', 1, 4, 'default.jpg', CURRENT_TIMESTAMP),
    ('Unraveling the Mysteries of Geometry', 'Explore the principles and applications of geometry in real-world scenarios.', 'Geometry is a fascinating branch of mathematics with diverse applications. In this blog post, we unravel the mysteries of geometry, covering fundamental principles and their real-world significance.', 1, 4, 'default.jpg', CURRENT_TIMESTAMP),
    ('Journey into Calculus Basics', 'Introduction to the basics of calculus and its practical applications.', 'Embark on a journey into the realm of calculus with this blog post. Gain insights into the basics of calculus and discover its practical applications in various scientific and engineering fields.', 1, 4, 'default.jpg', CURRENT_TIMESTAMP),
    ('Essential Statistics for Beginners', 'Learn fundamental statistical concepts and methods for data analysis.', 'Statistics is a powerful tool for analyzing and interpreting data. In this blog post, we cover essential statistical concepts for beginners, providing a solid foundation for understanding and applying statistical methods.', 1, 4, 'default.jpg', CURRENT_TIMESTAMP),
    ('Mastering Trigonometry Principles', 'Master the principles of trigonometry and their applications.', 'Trigonometry is a key branch of mathematics with applications in various fields. This blog post guides you through mastering the principles of trigonometry, from basic concepts to advanced applications.', 1, 4, 'default.jpg', CURRENT_TIMESTAMP),
    ('The Art of Web Design', 'Explore the principles and aesthetics of web design.', 'This blog post dives into the art of web design, covering principles, aesthetics, and the creative process behind designing visually appealing and user-friendly websites. Whether you are a beginner or an experienced designer, discover the key elements of effective web design.', 1, 5, 'default.jpg', CURRENT_TIMESTAMP),
    ('Responsive Web Design Strategies', 'Master the strategies for creating responsive and mobile-friendly websites.', 'In this blog post, we explore strategies for mastering responsive web design. Learn techniques and best practices to ensure your websites are accessible and optimized across various devices, providing a seamless user experience.', 1, 5, 'default.jpg', CURRENT_TIMESTAMP),
    ('Advanced CSS Techniques Unleashed', 'Explore advanced CSS techniques for modern web development.', 'Take your web development skills to the next level with this blog post on advanced CSS techniques. Discover tips, tricks, and techniques to enhance your CSS skills and create stunning and dynamic web pages.', 1, 5, 'default.jpg', CURRENT_TIMESTAMP),
    ('Designing User-Friendly Interfaces', 'Create intuitive and user-friendly interfaces for websites and applications.', 'User interface (UI) design is crucial for a positive user experience. This blog post guides you through the process of designing interfaces that are not only visually appealing but also user-friendly, contributing to the overall success of your web projects.', 1, 5, 'default.jpg', CURRENT_TIMESTAMP),
    ('JavaScript for Web Designers', 'Learn JavaScript to enhance your web design skills.', 'JavaScript is a powerful scripting language that adds interactivity to websites. In this blog post, we explore how web designers can leverage JavaScript to enhance the functionality and user experience of their web designs.', 1, 5, 'default.jpg', CURRENT_TIMESTAMP),
    ('Essentials of Web Development', 'Learn the fundamental principles of web development.', 'This blog post serves as a comprehensive guide to the essentials of web development. Whether youre a beginner or an experienced developer, explore the fundamental principles and best practices that form the foundation of successful web development.', 1, 6, 'default.jpg', CURRENT_TIMESTAMP),
    ('Responsive Web Design and Development', 'Master the art of creating responsive and mobile-friendly websites.', 'In this blog post, we delve into the world of responsive web design and development. Explore techniques and strategies to ensure your websites are adaptive to various screen sizes and devices, providing a seamless user experience.', 1, 6, 'default.jpg', CURRENT_TIMESTAMP),
    ('Advanced JavaScript Programming Techniques', 'Explore advanced JavaScript techniques for modern web development.', 'Take your JavaScript skills to the next level with this blog post on advanced programming techniques. Discover tips, tricks, and best practices to enhance the functionality and interactivity of your web applications.', 1, 6, 'default.jpg', CURRENT_TIMESTAMP),
    ('Server-side Development with Node.js', 'Learn server-side web development using Node.js.', 'Node.js is a powerful platform for server-side development. This blog post guides you through the basics of Node.js and explores how to leverage it for building scalable and efficient web applications.', 1, 6, 'default.jpg', CURRENT_TIMESTAMP),
    ('Database Design and Management for Web Applications', 'Understand database design principles and management for web applications.', 'A well-designed database is crucial for the success of web applications. This blog post covers essential principles of database design and management, providing insights into creating efficient and scalable web applications.', 1, 6, 'default.jpg', CURRENT_TIMESTAMP);

-- Add Comments
INSERT INTO Comments (blog_id, user_id, comment_text) VALUES
    (1, 1, 'This blog is incredibly helpful! The tips on incorporating new words into daily reading are practical and effective.'),
    (1, 2, 'I''ve been using the suggested language apps, and my vocabulary has expanded significantly. Thanks for the valuable insights!'),
    (2, 3, 'Grammar has always been a challenge for me, but this blog breaks down the rules in a way that''s easy to understand. Great resource!'),
    (2, 4, 'The section on common grammar pitfalls was eye-opening. I''m more confident in my writing now. Thank you!'),
    (3, 5, 'A literary journey indeed! Your exploration of classic literature has inspired me to revisit some timeless pieces. Wonderful blog!'),
    (3, 6, 'The insights into the themes and characters of classic literature are fascinating. I''ve added a few books to my reading list!'),
    (4, 7, 'As someone working in a corporate setting, this blog has been a game-changer for me. The business communication tips are spot on!'),
    (4, 8, 'The strategies for professional emails are practical and straightforward. I''m seeing a positive impact on my communication at work.'),
    (5, 9, 'The creative writing techniques mentioned here have added a new dimension to my writing. Thank you for the inspiration!'),
    (5, 10, 'I appreciate the emphasis on expressing emotions through prose. This blog has reignited my passion for creative writing.'),
    (6, 11, 'A clear and concise introduction to chemistry basics. This blog is a perfect starting point for beginners like me.'),
    (6, 12, 'Chemistry has always intimidated me, but this blog made the fundamentals accessible. Looking forward to learning more!'),
    (7, 13, 'Organic chemistry always seemed complex, but this blog provided a captivating overview. Excited to explore this field further!'),
    (7, 14, 'The real-world applications highlighted in this blog make organic chemistry even more intriguing. Great job explaining!'),
    (8, 15, 'Inorganic chemistry can be challenging, but this blog breaks down the principles in a way that''s easy to grasp. Well done!'),
    (8, 16, 'The journey through inorganic chemistry principles was informative and engaging. I appreciate the clarity in explanations.'),
    (9, 17, 'The insights into analytical chemistry techniques are valuable for anyone interested in the field. Great explanations!'),
    (9, 18, 'I''ve always been curious about analytical chemistry, and this blog provided a comprehensive overview. Well done!'),
    (10, 19, 'Physical chemistry applications are more diverse than I imagined. This blog broadened my understanding of the field.'),
    (10, 20, 'The real-world examples in this blog make the applications of physical chemistry easier to grasp. Informative and well-written!'),
    (11, 21, 'As a physics enthusiast, I found this blog on classical mechanics to be an excellent resource. Clear explanations and detailed content.'),
    (11, 22, 'The blog provides a solid foundation in classical mechanics. The historical context adds an interesting dimension to the subject.'),
    (12, 23, 'Quantum physics has always intrigued me, and this blog serves as a great introduction. The concepts are explained in an approachable manner.'),
    (12, 24, 'The section on quantum entanglement was mind-bending! Excited to dive deeper into the world of quantum physics.'),
    (13, 25, 'This blog provides a comprehensive overview of thermodynamics and statistical mechanics. The examples make complex concepts easier to understand.'),
    (13, 26, 'As a student studying physics, I found the explanations on thermodynamics and statistical mechanics to be extremely helpful.'),
    (14, 27, 'The principles of electromagnetism are well-explained in this blog. The applications in technology and everyday life are fascinating.'),
    (14, 28, 'As an engineering student, I appreciate the practical insights into electromagnetism. Great content!'),
    (15, 29, 'Nuclear physics is a captivating field, and this blog does an excellent job covering the fundamentals. The historical context adds depth.'),
    (15, 30, 'The blog provides a clear overview of nuclear physics concepts. Excited to explore more about nuclear reactions.'),
    (16, 1, 'A helpful guide for mastering algebraic concepts. The step-by-step explanations make it easy to follow.'),
    (16, 2, 'I struggled with algebra, but this blog has been a lifesaver. The examples and practice problems are really beneficial.'),
    (17, 3, 'Geometry has always been challenging for me, but this blog made it much more accessible. The real-world applications are a nice touch.'),
    (17, 4, 'The blog provides a comprehensive overview of geometry principles. The explanations are clear, making it easier to understand.'),
    (18, 5, 'A great introduction to the basics of calculus. The practical applications discussed in the blog are insightful.'),
    (18, 6, 'The blog provides a solid foundation for anyone learning calculus. The examples and explanations are well-executed.'),
    (19, 7, 'Statistics can be intimidating, but this blog breaks down the fundamental concepts in an easy-to-understand manner. Highly recommended!'),
    (19, 8, 'I''ve always found statistics challenging, but this blog clarified many concepts for me. The examples are very helpful.'),
    (20, 9, 'Trigonometry can be complex, but this blog provides a clear and concise guide to mastering its principles. Well-written and informative.'),
    (20, 10, 'I appreciate the emphasis on practical applications in this blog. The trigonometry principles are explained in a way that''s easy to understand.'),
    (21, 11, 'This blog delves into the artistic aspects of web design. The principles and creative process are well-explained. Great insights!'),
    (21, 12, 'As a beginner in web design, this blog has been instrumental in understanding the creative process. The examples are inspiring.'),
    (22, 13, 'The strategies for creating responsive websites are practical and effective. This blog is a must-read for web developers.'),
    (22, 14, 'I''ve been struggling with making my websites responsive, but this blog provided clear strategies. Very helpful content!'),
    (23, 15, 'The advanced CSS techniques discussed in this blog took my web development skills to the next level. Valuable insights and examples.'),
    (23, 16, 'CSS can be challenging, but this blog breaks down advanced techniques in a way that''s easy to understand. Great resource for developers.'),
    (24, 17, 'User-friendly interfaces are crucial, and this blog provides practical guidance for designers. The tips on intuitive design are especially useful.'),
    (24, 18, 'I''m a UI designer, and this blog resonated with me. The emphasis on user-friendly interfaces is spot on. Well-written and informative.'),
    (25, 19, 'JavaScript can enhance web design, and this blog serves as a great introduction. The examples and explanations are clear and concise.'),
    (25, 20, 'I''ve been wanting to learn JavaScript for web design, and this blog provided a solid foundation. Excited to implement these techniques!'),
    (26, 21, 'A comprehensive guide to the essentials of web development. The foundational principles are well-explained. Great content!'),
    (26, 22, 'Whether youre a beginner or an experienced developer, this blog covers the essentials of web development. The tips are practical and valuable.');